import csv
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional

from latch.types.directory import LatchDir, LatchOutputDir
from latch.types.file import LatchFile
from latch.types.metadata import (
    Fork,
    ForkBranch,
    LatchRule,
    NextflowParameter,
    Params,
    Section,
    Spoiler,
    Text,
)


@dataclass(frozen=True)
class SampleSheet:
    sampleid: str
    forwardreads: LatchFile
    reversereads: Optional[LatchFile]
    run: Optional[str]


def custom_samplesheet_constructor(samples: List[SampleSheet]) -> Path:
    samplesheet = Path("/root/samplesheet.csv")

    columns = ["sampleID", "forwardReads", "reverseReads", "run"]

    with open(samplesheet, "w") as f:
        writer = csv.DictWriter(f, columns, delimiter=",")
        writer.writeheader()

        for sample in samples:
            row_data = {
                "sampleID": sample.sampleid,
                "forwardReads": sample.forwardreads,
                "reverseReads": sample.reversereads if sample.reversereads else "",
                "run": sample.run if sample.run else "",
            }
            writer.writerow(row_data)

    return samplesheet


flow = [
    Section(
        "Input/Output",
        Fork(
            "input_source",
            "",
            sheet=ForkBranch(
                "Sample Sheet",
                Params(
                    "input",
                ),
            ),
            fasta=ForkBranch(
                "Input Fasta",
                Params(
                    "input_fasta",
                ),
            ),
            folder=ForkBranch(
                "Input Folder with Regex",
                Params(
                    "input_folder",
                    "extension",
                    "multiple_sequencing_runs",
                ),
            ),
        ),
        Text(""),
        Params(
            "metadata",
        ),
    ),
    Section(
        "Primers",
        Params(
            "FW_primer",
            "RV_primer",
        ),
        Spoiler(
            "Advanced Arguments",
            Params(
                "retain_untrimmed",
                "cutadapt_min_overlap",
                "cutadapt_max_error_rate",
                "double_primer",
                "ignore_failed_trimming",
            ),
        ),
    ),
    Section(
        "Taxonomic Classification",
        Params(
            "dada_ref_taxonomy",
            "qiime_ref_taxonomy",
            "kraken2_ref_taxonomy",
            "sintax_ref_taxonomy",
        ),
        Spoiler(
            "Advanced Arguments",
            Params(
                "dada_ref_tax_custom",
                "dada_ref_tax_custom_sp",
                "dada_assign_taxlevels",
                "cut_dada_ref_taxonomy",
                "dada_addspecies_allowmultiple",
                "dada_taxonomy_rc",
                "pplace_tree",
                "pplace_aln",
                "pplace_model",
                "pplace_alnmethod",
                "pplace_taxonomy",
                "qiime_ref_tax_custom",
                "classifier",
                "kraken2_ref_tax_custom",
                "kraken2_assign_taxlevels",
                "kraken2_confidence",
                "addsh",
                "cut_its",
                "its_partial",
            ),
        ),
    ),
    Section(
        "Output Directory",
        Params("run_name"),
        Text("Parent directory for outputs"),
        Params("outdir"),
    ),
    Spoiler(
        "Advanced Options",
        Spoiler(
            "Sequencing Input Options",
            Params(
                "illumina_novaseq",
                "pacbio",
                "iontorrent",
                "single_end",
                "illumina_pe_its",
                "min_read_counts",
                "ignore_empty_input_files",
            ),
        ),
        Spoiler(
            "Read Trimming and Quality Filtering",
            Params(
                "trunclenf",
                "trunclenr",
                "trunc_qmin",
                "trunc_rmin",
                "max_ee",
                "min_len",
                "max_len",
                "ignore_failed_filtering",
            ),
        ),
        Spoiler(
            "Amplicon Sequence Variants (ASV) Calculation and Post-processing",
            Params(
                "sample_inference",
                "concatenate_reads",
                "vsearch_cluster",
                "vsearch_cluster_id",
                "filter_ssu",
                "min_len_asv",
                "max_len_asv",
                "filter_codons",
                "orf_start",
                "orf_end",
                "stop_codons",
            ),
        ),
        Spoiler(
            "Multi-region Analysis",
            Params(
                "multiregion",
                "sidle_ref_taxonomy",
                "sidle_ref_tax_custom",
                "sidle_ref_tree_custom",
            ),
        ),
        Spoiler(
            "ASV Filtering",
            Params(
                "exclude_taxa",
                "min_frequency",
                "min_samples",
            ),
        ),
        Spoiler(
            "Downstream Analysis",
            Params(
                "metadata_category",
                "metadata_category_barplot",
                "qiime_adonis_formula",
                "picrust",
                "sbdiexport",
                "diversity_rarefaction_depth",
                "tax_agglom_min",
                "tax_agglom_max",
            ),
        ),
        Spoiler(
            "Differential Abundance Analysis",
            Params(
                "ancom_sample_min_count",
                "ancom",
                "ancombc",
                "ancombc_formula",
                "ancombc_formula_reflvl",
                "ancombc_effect_size",
                "ancombc_significance",
            ),
        ),
        Spoiler(
            "Step Skipping",
            Params(
                "skip_fastqc",
                "skip_cutadapt",
                "skip_dada_quality",
                "skip_barrnap",
                "skip_qiime",
                "skip_qiime_downstream",
                "skip_taxonomy",
                "skip_dada_taxonomy",
                "skip_dada_addspecies",
                "skip_barplot",
                "skip_abundance_tables",
                "skip_alpha_rarefaction",
                "skip_diversity_indices",
                "skip_multiqc",
                "skip_report",
            ),
        ),
        Spoiler(
            "Saving Steps",
            Params(
                "save_intermediates",
            ),
        ),
        Spoiler(
            "Other Options",
            Params(
                "email",
                "seed",
                "multiqc_methods_description",
            ),
        ),
        Spoiler(
            "Resource Limits",
            Params(
                "max_cpus",
                "max_memory",
                "max_time",
            ),
        ),
        Spoiler(
            "Report Customization",
            Params(
                "report_template",
                "report_css",
                "report_logo",
                "report_title",
                "report_abstract",
            ),
        ),
    ),
]


generated_parameters = {
    "input_source": NextflowParameter(),
    "run_name": NextflowParameter(
        type=str,
        display_name="Run Name",
        description="Name of run",
        batch_table_column=True,
        rules=[
            LatchRule(
                regex=r"^[a-zA-Z0-9_-]+$",
                message="Run name must contain only letters, digits, underscores, and dashes. No spaces are allowed.",
            )
        ],
    ),
    "input": NextflowParameter(
        type=List[SampleSheet],
        display_name="Sample Sheet",
        samplesheet=True,
        samplesheet_constructor=custom_samplesheet_constructor,
    ),
    "input_fasta": NextflowParameter(
        type=Optional[LatchFile],
        display_name="ASV/OTU FASTA File",
        default=None,
        section_title=None,
        description="Path to ASV/OTU fasta file",
    ),
    "input_folder": NextflowParameter(
        type=Optional[LatchDir],
        display_name="Input Folder",
        default=None,
        section_title=None,
        description="Path to folder containing zipped FastQ files",
    ),
    "FW_primer": NextflowParameter(
        type=Optional[str],
        display_name="Forward Primer",
        default=None,
        section_title=None,
        description="Forward primer sequence",
    ),
    "RV_primer": NextflowParameter(
        type=Optional[str],
        display_name="Reverse Primer",
        default=None,
        section_title=None,
        description="Reverse primer sequence",
    ),
    "metadata": NextflowParameter(
        type=Optional[LatchFile],
        display_name="Metadata Sheet",
        default=None,
        section_title=None,
        description="Path to metadata sheet, when missing most downstream analysis are skipped (barplots, PCoA plots, ...).",
    ),
    "multiregion": NextflowParameter(
        type=Optional[LatchFile],
        display_name="Multi-region Definition Sheet",
        default=None,
        section_title=None,
        description="Path to multi-region definition sheet, for multi-region analysis with Sidle",
    ),
    "outdir": NextflowParameter(
        type=LatchOutputDir,
        display_name="Output Directory",
        default=None,
        section_title=None,
        results_paths=[Path("/"), Path("/pipeline_info/execution_report.html")],
        description="The output directory where the results will be saved.",
    ),
    "save_intermediates": NextflowParameter(
        type=bool,
        display_name="Save Intermediate Results",
        default=None,
        section_title=None,
        description="Save intermediate results such as QIIME2's qza and qzv files",
    ),
    "email": NextflowParameter(
        type=Optional[str],
        display_name="Email Address",
        default=None,
        section_title=None,
        description="Email address for completion summary.",
    ),
    "illumina_novaseq": NextflowParameter(
        type=bool,
        display_name="Illumina NovaSeq Data",
        default=None,
        description="If data has binned quality scores such as Illumina NovaSeq",
    ),
    "pacbio": NextflowParameter(
        type=bool,
        display_name="PacBio Data",
        default=None,
        section_title=None,
        description="If data is single-ended PacBio reads instead of Illumina",
    ),
    "iontorrent": NextflowParameter(
        type=bool,
        display_name="IonTorrent Data",
        default=None,
        section_title=None,
        description="If data is single-ended IonTorrent reads instead of Illumina",
    ),
    "single_end": NextflowParameter(
        type=bool,
        display_name="Single-end Illumina Data",
        default=None,
        section_title=None,
        description="If data is single-ended Illumina reads instead of paired-end",
    ),
    "illumina_pe_its": NextflowParameter(
        type=bool,
        display_name="Illumina PE ITS Data",
        default=None,
        section_title=None,
        description="If analysing ITS amplicons or any other region with large length variability with Illumina paired end reads",
    ),
    "multiple_sequencing_runs": NextflowParameter(
        type=bool,
        display_name="Multiple Sequencing Runs",
        default=None,
        section_title=None,
        description="If using `--input_folder`: samples were sequenced in multiple sequencing runs",
    ),
    "extension": NextflowParameter(
        type=Optional[str],
        display_name="File Extension",
        default="/*_R{1,2}_001.fastq.gz",
        section_title=None,
        description="If using `--input_folder`: naming of sequencing files",
    ),
    "min_read_counts": NextflowParameter(
        type=Optional[int],
        display_name="Minimum Read Count",
        default=1,
        section_title=None,
        description="Set read count threshold for failed samples.",
    ),
    "ignore_empty_input_files": NextflowParameter(
        type=bool,
        display_name="Ignore Empty Input Files",
        default=None,
        section_title=None,
        description="Ignore input files with too few reads.",
    ),
    "retain_untrimmed": NextflowParameter(
        type=bool,
        display_name="Retain Untrimmed Reads",
        default=None,
        description="Cutadapt will retain untrimmed reads, choose only if input reads are not expected to contain primer sequences.",
    ),
    "cutadapt_min_overlap": NextflowParameter(
        type=Optional[int],
        display_name="Cutadapt Minimum Overlap",
        default=3,
        section_title=None,
        description="Sets the minimum overlap for valid matches of primer sequences with reads for cutadapt (-O).",
    ),
    "cutadapt_max_error_rate": NextflowParameter(
        type=Optional[float],
        display_name="Cutadapt Maximum Error Rate",
        default=0.1,
        section_title=None,
        description="Sets the maximum error rate for valid matches of primer sequences with reads for cutadapt (-e).",
    ),
    "double_primer": NextflowParameter(
        type=bool,
        display_name="Double Primer",
        default=None,
        section_title=None,
        description="Cutadapt will be run twice to ensure removal of potential double primers",
    ),
    "ignore_failed_trimming": NextflowParameter(
        type=bool,
        display_name="Ignore Failed Trimming",
        default=None,
        section_title=None,
        description="Ignore files with too few reads after trimming.",
    ),
    "trunclenf": NextflowParameter(
        type=Optional[int],
        display_name="Forward Read Truncation Length",
        default=None,
        description="DADA2 read truncation value for forward strand, set this to 0 for no truncation",
    ),
    "trunclenr": NextflowParameter(
        type=Optional[int],
        display_name="Reverse Read Truncation Length",
        default=None,
        section_title=None,
        description="DADA2 read truncation value for reverse strand, set this to 0 for no truncation",
    ),
    "trunc_qmin": NextflowParameter(
        type=Optional[int],
        display_name="Minimum Quality Score for Truncation",
        default=25,
        section_title=None,
        description="If --trunclenf and --trunclenr are not set, these values will be automatically determined using this median quality score",
    ),
    "trunc_rmin": NextflowParameter(
        type=Optional[float],
        display_name="Minimum Read Retention Fraction",
        default=0.75,
        section_title=None,
        description="Assures that values chosen with --trunc_qmin will retain a fraction of reads.",
    ),
    "max_ee": NextflowParameter(
        type=Optional[int],
        display_name="Maximum Expected Errors",
        default=2,
        section_title=None,
        description="DADA2 read filtering option",
    ),
    "min_len": NextflowParameter(
        type=Optional[int],
        display_name="Minimum Read Length",
        default=50,
        section_title=None,
        description="DADA2 read filtering option",
    ),
    "max_len": NextflowParameter(
        type=Optional[int],
        display_name="Maximum Read Length",
        default=None,
        section_title=None,
        description="DADA2 read filtering option",
    ),
    "ignore_failed_filtering": NextflowParameter(
        type=bool,
        display_name="Ignore Failed Filtering",
        default=None,
        section_title=None,
        description="Ignore files with too few reads after quality filtering.",
    ),
    "sample_inference": NextflowParameter(
        type=Optional[str],
        display_name="Sample Inference Mode",
        default="independent",
        description='Mode of sample inference: "independent", "pooled" or "pseudo"',
    ),
    "concatenate_reads": NextflowParameter(
        type=bool,
        display_name="Concatenate Reads",
        default=None,
        section_title=None,
        description="Not recommended: When paired end reads are not sufficiently overlapping for merging.",
    ),
    "vsearch_cluster": NextflowParameter(
        type=bool,
        display_name="VSEARCH Clustering",
        default=None,
        section_title="ASV post processing",
        description="Post-cluster ASVs with VSEARCH",
    ),
    "vsearch_cluster_id": NextflowParameter(
        type=Optional[float],
        display_name="VSEARCH Clustering Identity",
        default=0.97,
        section_title=None,
        description="Pairwise Identity value used when post-clustering ASVs if `--vsearch_cluster` option is used (default: 0.97).",
    ),
    "filter_ssu": NextflowParameter(
        type=Optional[str],
        display_name="SSU Filtering",
        default=None,
        section_title=None,
        description='Enable SSU filtering. Comma separated list of kingdoms (domains) in Barrnap, a combination (or one) of "bac", "arc", "mito", and "euk". ASVs that have their lowest evalue in that kingdoms are kept.',
    ),
    "min_len_asv": NextflowParameter(
        type=Optional[int],
        display_name="Minimum ASV Length",
        default=None,
        section_title=None,
        description="Minimal ASV length",
    ),
    "max_len_asv": NextflowParameter(
        type=Optional[int],
        display_name="Maximum ASV Length",
        default=None,
        section_title=None,
        description="Maximum ASV length",
    ),
    "filter_codons": NextflowParameter(
        type=bool,
        display_name="Filter Codons",
        default=None,
        section_title=None,
        description="Filter ASVs based on codon usage",
    ),
    "orf_start": NextflowParameter(
        type=Optional[int],
        display_name="ORF Start Position",
        default=1,
        section_title=None,
        description="Starting position of codon tripletts",
    ),
    "orf_end": NextflowParameter(
        type=Optional[int],
        display_name="ORF End Position",
        default=None,
        section_title=None,
        description="Ending position of codon tripletts",
    ),
    "stop_codons": NextflowParameter(
        type=Optional[str],
        display_name="Stop Codons",
        default="TAA,TAG",
        section_title=None,
        description="Define stop codons",
    ),
    "dada_ref_taxonomy": NextflowParameter(
        type=Optional[str],
        display_name="DADA2 Reference Taxonomy",
        default="silva=138",
        description="Name of supported database, and optionally also version number",
    ),
    "dada_ref_tax_custom": NextflowParameter(
        type=Optional[str],
        display_name="Custom DADA2 Reference Taxonomy",
        default=None,
        section_title=None,
        description="Path to a custom DADA2 reference taxonomy database",
    ),
    "dada_ref_tax_custom_sp": NextflowParameter(
        type=Optional[str],
        display_name="Custom DADA2 Species Reference Taxonomy",
        default=None,
        section_title=None,
        description="Path to a custom DADA2 reference taxonomy database for species assignment",
    ),
    "dada_assign_taxlevels": NextflowParameter(
        type=Optional[str],
        display_name="DADA2 Taxonomic Levels",
        default=None,
        section_title=None,
        description="Comma separated list of taxonomic levels used in DADA2's assignTaxonomy function",
    ),
    "cut_dada_ref_taxonomy": NextflowParameter(
        type=bool,
        display_name="Cut DADA2 Reference Taxonomy",
        default=None,
        section_title=None,
        description="If the expected amplified sequences are extracted from the DADA2 reference taxonomy database",
    ),
    "dada_addspecies_allowmultiple": NextflowParameter(
        type=bool,
        display_name="Allow Multiple DADA2 Species",
        default=None,
        section_title=None,
        description="If multiple exact matches against different species are returned",
    ),
    "dada_taxonomy_rc": NextflowParameter(
        type=bool,
        display_name="DADA2 Reverse Complement Taxonomy",
        default=None,
        section_title=None,
        description="If reverse-complement of each sequences will be also tested for classification",
    ),
    "pplace_tree": NextflowParameter(
        type=Optional[str],
        display_name="Phylogenetic Placement Tree",
        default=None,
        section_title=None,
        description="Newick file with reference phylogenetic tree. Requires also `--pplace_aln` and `--pplace_model`.",
    ),
    "pplace_aln": NextflowParameter(
        type=Optional[str],
        display_name="Phylogenetic Placement Alignment",
        default=None,
        section_title=None,
        description="File with reference sequences. Requires also `--pplace_tree` and `--pplace_model`.",
    ),
    "pplace_model": NextflowParameter(
        type=Optional[str],
        display_name="Phylogenetic Placement Model",
        default=None,
        section_title=None,
        description="Phylogenetic model to use in placement, e.g. 'LG+F' or 'GTR+I+F'. Requires also `--pplace_tree` and `--pplace_aln`.",
    ),
    "pplace_alnmethod": NextflowParameter(
        type=Optional[str],
        display_name="Phylogenetic Placement Alignment Method",
        default="hmmer",
        section_title=None,
        description='Method used for alignment, "hmmer" or "mafft"',
    ),
    "pplace_taxonomy": NextflowParameter(
        type=Optional[str],
        display_name="Phylogenetic Placement Taxonomy",
        default=None,
        section_title=None,
        description="Tab-separated file with taxonomy assignments of reference sequences.",
    ),
    "qiime_ref_taxonomy": NextflowParameter(
        type=Optional[str],
        display_name="QIIME2 Reference Taxonomy",
        default=None,
        section_title=None,
        description="Name of supported database, and optionally also version number",
    ),
    "qiime_ref_tax_custom": NextflowParameter(
        type=Optional[str],
        display_name="Custom QIIME2 Reference Taxonomy",
        default=None,
        section_title=None,
        description="Path to files of a custom QIIME2 reference taxonomy database (tarball, or two comma-separated files)",
    ),
    "classifier": NextflowParameter(
        type=Optional[str],
        display_name="QIIME2 Classifier",
        default=None,
        section_title=None,
        description="Path to QIIME2 trained classifier file (typically *-classifier.qza)",
    ),
    "kraken2_ref_taxonomy": NextflowParameter(
        type=Optional[str],
        display_name="Kraken2 Reference Taxonomy",
        default=None,
        section_title=None,
        description="Name of supported database, and optionally also version number",
    ),
    "kraken2_ref_tax_custom": NextflowParameter(
        type=Optional[str],
        display_name="Custom Kraken2 Reference Taxonomy",
        default=None,
        section_title=None,
        description="Path to a custom Kraken2 reference taxonomy database (*.tar.gz|*.tgz archive or folder)",
    ),
    "kraken2_assign_taxlevels": NextflowParameter(
        type=Optional[str],
        display_name="Kraken2 Taxonomic Levels",
        default=None,
        section_title=None,
        description="Comma separated list of taxonomic levels used in Kraken2. Will overwrite default values.",
    ),
    "kraken2_confidence": NextflowParameter(
        type=Optional[float],
        display_name="Kraken2 Confidence Score",
        default=0.0,
        section_title=None,
        description="Confidence score threshold for taxonomic classification.",
    ),
    "sintax_ref_taxonomy": NextflowParameter(
        type=Optional[str],
        display_name="SINTAX Reference Taxonomy",
        default=None,
        section_title=None,
        description="Name of supported database, and optionally also version number",
    ),
    "addsh": NextflowParameter(
        type=bool,
        display_name="Add UNITE Species Hypotheses",
        default=None,
        section_title=None,
        description="If ASVs should be assigned to UNITE species hypotheses (SHs). Only relevant for ITS data.",
    ),
    "cut_its": NextflowParameter(
        type=Optional[str],
        display_name="ITS Region for Taxonomy",
        default="none",
        section_title=None,
        description='Part of ITS region to use for taxonomy assignment: "full", "its1", or "its2"',
    ),
    "its_partial": NextflowParameter(
        type=Optional[int],
        display_name="Partial ITS Sequence Cutoff",
        default=0,
        section_title=None,
        description="Cutoff for partial ITS sequences. Only full sequences by default.",
    ),
    "sidle_ref_taxonomy": NextflowParameter(
        type=Optional[str],
        display_name="SIDLE Reference Taxonomy",
        default=None,
        description="Name of supported database, and optionally also version number",
    ),
    "sidle_ref_tax_custom": NextflowParameter(
        type=Optional[str],
        display_name="Custom SIDLE Reference Taxonomy",
        default=None,
        section_title=None,
        description="Comma separated paths to three files: reference taxonomy sequences (*.fasta), reference taxonomy strings (*.txt)",
    ),
    "sidle_ref_tree_custom": NextflowParameter(
        type=Optional[str],
        display_name="Custom SIDLE Reference Tree",
        default=None,
        section_title=None,
        description="Path to SIDLE reference taxonomy tree (*.qza)",
    ),
    "exclude_taxa": NextflowParameter(
        type=Optional[str],
        display_name="Exclude Taxa",
        default="mitochondria,chloroplast",
        description='Comma separated list of unwanted taxa, to skip taxa filtering use "none"',
    ),
    "min_frequency": NextflowParameter(
        type=Optional[int],
        display_name="Minimum Frequency",
        default=1,
        section_title=None,
        description="Abundance filtering",
    ),
    "min_samples": NextflowParameter(
        type=Optional[int],
        display_name="Minimum Samples",
        default=1,
        section_title=None,
        description="Prevalence filtering",
    ),
    "metadata_category": NextflowParameter(
        type=Optional[str],
        display_name="Metadata Categories for Statistics",
        default=None,
        description="Comma separated list of metadata column headers for statistics.",
    ),
    "metadata_category_barplot": NextflowParameter(
        type=Optional[str],
        display_name="Metadata Categories for Barplots",
        default=None,
        section_title=None,
        description="Comma separated list of metadata column headers for plotting average relative abundance barplots.",
    ),
    "qiime_adonis_formula": NextflowParameter(
        type=Optional[str],
        display_name="QIIME2 ADONIS Formula",
        default=None,
        section_title=None,
        description="Formula for QIIME2 ADONIS metadata feature importance test for beta diversity distances",
    ),
    "picrust": NextflowParameter(
        type=bool,
        display_name="Predict Functional Potential",
        default=None,
        section_title=None,
        description="If the functional potential of the bacterial community is predicted.",
    ),
    "sbdiexport": NextflowParameter(
        type=bool,
        display_name="Export SBDI Format",
        default=None,
        section_title=None,
        description="If data should be exported in SBDI (Swedish biodiversity infrastructure) Excel format.",
    ),
    "diversity_rarefaction_depth": NextflowParameter(
        type=Optional[int],
        display_name="Diversity Rarefaction Depth",
        default=500,
        section_title=None,
        description="Minimum rarefaction depth for diversity analysis. Any sample below that threshold will be removed.",
    ),
    "tax_agglom_min": NextflowParameter(
        type=Optional[int],
        display_name="Minimum Taxonomy Agglomeration Level",
        default=2,
        section_title=None,
        description="Minimum taxonomy agglomeration level for taxonomic classifications",
    ),
    "tax_agglom_max": NextflowParameter(
        type=Optional[int],
        display_name="Maximum Taxonomy Agglomeration Level",
        default=6,
        section_title=None,
        description="Maximum taxonomy agglomeration level for taxonomic classifications",
    ),
    "ancom_sample_min_count": NextflowParameter(
        type=Optional[int],
        display_name="ANCOM Minimum Sample Count",
        default=1,
        description="Minimum sample counts to retain a sample for ANCOM analysis. Any sample below that threshold will be removed.",
    ),
    "ancom": NextflowParameter(
        type=bool,
        display_name="Perform ANCOM Analysis",
        default=None,
        section_title=None,
        description="Perform differential abundance analysis with ANCOM",
    ),
    "ancombc": NextflowParameter(
        type=bool,
        display_name="Perform ANCOM-BC Analysis",
        default=None,
        section_title=None,
        description="Perform differential abundance analysis with ANCOMBC",
    ),
    "ancombc_formula": NextflowParameter(
        type=Optional[str],
        display_name="ANCOM-BC Formula",
        default=None,
        section_title=None,
        description="Formula to perform differential abundance analysis with ANCOMBC",
    ),
    "ancombc_formula_reflvl": NextflowParameter(
        type=Optional[str],
        display_name="ANCOM-BC Formula Reference Level",
        default=None,
        section_title=None,
        description="Reference level for `--ancombc_formula`",
    ),
    "ancombc_effect_size": NextflowParameter(
        type=Optional[float],
        display_name="ANCOM-BC Effect Size Threshold",
        default=1,
        section_title=None,
        description="Effect size threshold for differential abundance barplot for `--ancombc` and `--ancombc_formula`",
    ),
    "ancombc_significance": NextflowParameter(
        type=Optional[float],
        display_name="ANCOM-BC Significance Threshold",
        default=0.05,
        section_title=None,
        description="Significance threshold for differential abundance barplot for `--ancombc` and `--ancombc_formula`",
    ),
    "report_template": NextflowParameter(
        type=Optional[str],
        display_name="Report Template",
        default="${projectDir}/assets/report_template.Rmd",
        description="Path to Markdown file (Rmd)",
    ),
    "report_css": NextflowParameter(
        type=Optional[str],
        display_name="Report CSS",
        default="${projectDir}/assets/nf-core_style.css",
        section_title=None,
        description="Path to style file (css)",
    ),
    "report_logo": NextflowParameter(
        type=Optional[str],
        display_name="Report Logo",
        default="${projectDir}/assets/nf-core-ampliseq_logo_light_long.png",
        section_title=None,
        description="Path to logo file (png)",
    ),
    "report_title": NextflowParameter(
        type=Optional[str],
        display_name="Report Title",
        default="Summary of analysis results",
        section_title=None,
        description="String used as report title",
    ),
    "report_abstract": NextflowParameter(
        type=Optional[str],
        display_name="Report Abstract",
        default=None,
        section_title=None,
        description="Path to Markdown file (md) that replaces the 'Abstract' section",
    ),
    "skip_fastqc": NextflowParameter(
        type=bool,
        display_name="Skip FastQC",
        default=None,
        description="Skip FastQC",
    ),
    "skip_cutadapt": NextflowParameter(
        type=bool,
        display_name="Skip Cutadapt",
        default=None,
        section_title=None,
        description="Skip primer trimming with cutadapt. This is not recommended! Use only in case primer sequences were removed before and the data does not contain any primer sequences.",
    ),
    "skip_dada_quality": NextflowParameter(
        type=bool,
        display_name="Skip DADA2 Quality Check",
        default=None,
        section_title=None,
        description="Skip quality check with DADA2. Can only be skipped when `--trunclenf` and `--trunclenr` are set.",
    ),
    "skip_barrnap": NextflowParameter(
        type=bool,
        display_name="Skip Barrnap",
        default=None,
        section_title=None,
        description="Skip annotating SSU matches.",
    ),
    "skip_qiime": NextflowParameter(
        type=bool,
        display_name="Skip QIIME2",
        default=None,
        section_title=None,
        description="Skip all steps that are executed by QIIME2, including QIIME2 software download, taxonomy assignment by QIIME2, barplots, relative abundance tables, diversity analysis, differential abundance testing.",
    ),
    "skip_qiime_downstream": NextflowParameter(
        type=bool,
        display_name="Skip QIIME2 Downstream",
        default=None,
        section_title=None,
        description="Skip steps that are executed by QIIME2 except for taxonomic classification. Skip steps including barplots, relative abundance tables, diversity analysis, differential abundance testing.",
    ),
    "skip_taxonomy": NextflowParameter(
        type=bool,
        display_name="Skip Taxonomy",
        default=None,
        section_title=None,
        description="Skip taxonomic classification. Incompatible with `--sbdiexport`",
    ),
    "skip_dada_taxonomy": NextflowParameter(
        type=bool,
        display_name="Skip DADA2 Taxonomy",
        default=None,
        section_title=None,
        description="Skip taxonomic classification with DADA2",
    ),
    "skip_dada_addspecies": NextflowParameter(
        type=bool,
        display_name="Skip DADA2 Add Species",
        default=None,
        section_title=None,
        description="Skip species level when using DADA2 for taxonomic classification. This reduces the required memory dramatically under certain conditions. Incompatible with `--sbdiexport`",
    ),
    "skip_barplot": NextflowParameter(
        type=bool,
        display_name="Skip Barplot",
        default=None,
        section_title=None,
        description="Skip producing barplot",
    ),
    "skip_abundance_tables": NextflowParameter(
        type=bool,
        display_name="Skip Abundance Tables",
        default=None,
        section_title=None,
        description="Skip producing any relative abundance tables",
    ),
    "skip_alpha_rarefaction": NextflowParameter(
        type=bool,
        display_name="Skip Alpha Rarefaction",
        default=None,
        section_title=None,
        description="Skip alpha rarefaction",
    ),
    "skip_diversity_indices": NextflowParameter(
        type=bool,
        display_name="Skip Diversity Indices",
        default=None,
        section_title=None,
        description="Skip alpha and beta diversity analysis",
    ),
    "skip_multiqc": NextflowParameter(
        type=bool,
        display_name="Skip MultiQC",
        default=None,
        section_title=None,
        description="Skip MultiQC reporting",
    ),
    "skip_report": NextflowParameter(
        type=bool,
        display_name="Skip Summary Report",
        default=None,
        section_title=None,
        description="Skip Markdown summary report",
    ),
    "seed": NextflowParameter(
        type=Optional[int],
        display_name="Random Seed",
        default=100,
        description="Specifies the random seed.",
    ),
    "multiqc_methods_description": NextflowParameter(
        type=Optional[str],
        display_name="MultiQC Methods Description",
        default=None,
        section_title=None,
        description="Custom MultiQC yaml file containing HTML including a methods description.",
    ),
    "max_cpus": NextflowParameter(
        type=Optional[int],
        display_name="Max CPUs",
        default=16,
        description="Maximum number of CPUs that can be requested for any single job.",
    ),
    "max_memory": NextflowParameter(
        type=Optional[str],
        display_name="Max Memory",
        default="128.GB",
        section_title=None,
        description="Maximum amount of memory that can be requested for any single job.",
    ),
    "max_time": NextflowParameter(
        type=Optional[str],
        display_name="Max Time",
        default="240.h",
        section_title=None,
        description="Maximum amount of time that can be requested for any single job.",
    ),
}
